# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "MyRemixApp1_Custom"
client_id = "90b184c9e1337eecddfd43684b8fe35a"
application_url = "https://shopify-remix-app-custom.onrender.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://shopify-remix-app-custom.onrender.com/auth/callback",
  "https://shopify-remix-app-custom.onrender.com/auth/shopify/callback",
  "https://shopify-remix-app-custom.onrender.com/api/auth/callback",
  "https://shopify-remix-app-custom.onrender.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
